# This is a GNU make makefile

JS=assets/wasm.js
EXEC=wasm_exec.js
EXEC_SRC=misc/wasm/$(EXEC)
EXEC_DST=assets/$(EXEC)

all: $(JS) $(EXEC_DST)

$(JS): $(MAKEFILE_LIST) assets main.wasm
	echo "// Generated by $(MAKEFILE_LIST) $(shell date +%Y-%m-%d)" > $(JS)
	echo -n "wasm= '" >> $(JS)
	base64 -w 0 < main.wasm >> $(JS)
	echo -n "'" >> $(JS)

$(EXEC_DST):
	cp $(shell go env GOROOT)/$(EXEC_SRC) $(EXEC_DST)

main.wasm: main.go
	GOOS=js GOARCH=wasm go build -o main.wasm

assets:
	mkdir assets
